### ISSUE TITLE
Misssing something in 30 Days Of Solidity: Variables and Scopes

### ISSUE THREAD

**Issue by MBabattya** [Envoy-VC/100-Days-of-Solidity#3]
![Screenshot (381)](https://user-images.githubusercontent.com/105806841/200138977-cedb14e8-8383-4ac0-af2b-6d721ccba640.png)

getResult() function in the contract  D , in don't understand where the `storedData` state variable come
```storedData; //access the state variable```. i think it should be a `data` state variable

**Comment by envoy1084** [comment]
Yes, thank you for informing me; that was a typo.

**Comment by envoy1084** [comment]
Fixed it.
